### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by administrator22** [ngrie/rtmpie#10]
![image](https://user-images.githubusercontent.com/26051451/109740538-628d2f80-7c06-11eb-809b-dff19b355f82.png)

Hello,
You have done a great thing,and i think this is very useful for us.
I have done all the things as you say,but,I cannot open the UI on the browser,so ,could you help me find what's the problem.
And waiting for your user guides.
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by administrator22** [comment]
![image](https://user-images.githubusercontent.com/26051451/109743562-de3dab00-7c0b-11eb-939c-b8b378175476.png)

And I can't start streaming to this server with OBS.

**Comment by ngrie** [comment]
Please describe the steps you performed to install the software. Also, please post the output of `docker-compose logs php`.

**Comment by administrator22** [comment]
ok,I think something maybe wrong with my php.

apt-get install docker-ce docker-ce-cli containerd.io
apt-get install     apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
pub   rsa4096 2017-02-22 [SCEA]
uid           [ unknown] Docker Release (CE deb) <docker@docker.com>
sub   rsa4096 2017-02-22 [S]
add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io
apt-cache madison docker-ce
apt-get install docker-ce=5:20.10.4~3-0~ubuntu-xenial docker-ce-cli=5:20.10.4~3-0~ubuntu-xenial containerd.io
docker run hello-world
netstat -anptu | grep docker
curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
ls /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker-compose --version
docker-compose -f ./docker/docker-compose.prod.yaml build docker-compose -f ./docker/docker-compose.prod.yaml up -d
git clone https://github.com/ngrie/rtmpie.git
ls
cd rtmpie/
ls
docker-compose -f docker-compose.prod.yaml build docker-compose -f docker-compose.prod.yaml up -d
docker-compose -f ./docker-compose.prod.yaml build docker-compose -f ./docker-compose.prod.yaml up -d
vi docker-compose.prod.yaml
ls
docker-compose -f ./docker-compose.prod.yaml build docker-compose -f ./docker-compose.prod.yaml up -d
docker-compose --version
docker-compose -f ./docker-compose.prod.yaml build docker-compose -f ./docker-compose.prod.yaml up -d
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose -f ./docker-compose.prod.yaml build docker-compose -f ./docker-compose.prod.yaml up -d
docker-compose -f ./docker-compose.prod.yaml up -d
docker-compose ps
docker-compose -f ./docker-compose.prod.yaml build
docker-compose -f ./docker-compose.prod.yaml
docker-compose -f ./docker-compose.prod.yaml build
ls

cd docker/
ls
docker-compose -f ./docker-compose.prod.yaml build
composer require symfony/dotenv
apt install composer
docker-compose -f ./docker-compose.prod.yaml build
npm install --force
apt install npm
npm install --force
docker-compose -f ./docker-compose.prod.yaml build
ls
cd php/
ls
cd ..
ls
docker-compose -f ./docker-compose.prod.yaml build dock
docker-compose -f ./docker-compose.prod.yaml up -d
composer require symfony/dotenv
docker-compose -f ./docker-compose.prod.yaml up -d
ls
cd ..
ls
docker-compose -f ./docker/docker-compose.prod.yaml build
ls
cat docker-compose.yaml
docker-compose -f ./docker/docker-compose.yaml build
ls
cat docker-compose.prod.yaml
ls
cd config/
ls
cat services.yaml
cd ..
ls
cd config/
ls
ls packages/
cd ..
ls
cd src/
ls
cd ..
ls
cd migrations/
ls
cd ..
ls
cd bin
ls
ll console
cd ..
ls
cat rtmp_nginx_dev.conf
ls
cd migrations/
ls
cd ..
ls
docker pull docker.pkg.github.com/ngrie/rtmpie/php:latest
docker-compose -f ./docker/docker-compose.prod.yaml build
composer install --prefer-dist --no-dev --no-progress --no-suggest --no-interaction --optimize-autoloader
composer dump-autoload --no-dev --classmap-authoritative
composer require symfony/dotenv
composer self-update --2
which composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --install-dir /usr/bin --filename composer
php -r "unlink('composer-setup.php');"
docker-compose -f ./docker/docker-compose.prod.yaml build
composer self-update --2
composer require symfony/dotenv
php --ini
composer require symfony/dotenv
ls
ll
ls
cat composer.json
composer require symfony/dotenv
cat composer.lock
ls
docker-compose -f ./docker/docker-compose.prod.yaml up -d
ping google.com
ping www.baidu.com
composer require symfony/dotenv
ls
rm -rf composer.lock
composer clearcache
docker-compose -f ./docker/docker-compose.prod.yaml build
ls
composer update
vi composer.json
ls
composer update
docker-compose -f ./docker/docker-compose.prod.yaml build
docker-compose -f ./docker/docker-compose.prod.yaml up -d
netstat -anptu | grep docker
netstat -anptu | grep nginx

![20210306111852](https://user-images.githubusercontent.com/26051451/110193256-f90f5a00-7e6d-11eb-994b-454f9c8ed547.png)
![20210306111906](https://user-images.githubusercontent.com/26051451/110193260-fad91d80-7e6d-11eb-9c21-003a859c776c.png)

**Comment by ngrie** [comment]
Sorry, wrong command. Please run `docker-compose -f ./docker/docker-compose.prod.yaml logs php`

**Comment by administrator22** [comment]
![1](https://user-images.githubusercontent.com/26051451/110202891-545d3e80-7ea6-11eb-9b41-f5992f0d9f4d.jpg)


And anything I can do?

**Comment by ngrie** [comment]
Looks like you messed a few things up with your installation. Please remove your installation and install everything from scratch:

```
docker-compose -f ./docker/docker-compose.prod.yaml down
cd ..
rm -rf ./rtmpie
git clone https://github.com/ngrie/rtmpie.git
cd rtmpie
docker-compose -f ./docker/docker-compose.prod.yaml build
docker-compose -f ./docker/docker-compose.prod.yaml up -d
```

**Comment by ngrie** [comment]
Closed due to inactivity.
