### ISSUE TITLE
COPY failed: file not found in build context or excluded by .dockerignore

### ISSUE THREAD

**Issue by meesvw** [ngrie/rtmpie#19]
Complete error message:

`COPY failed: file not found in build context or excluded by .dockerignore: stat docker/nginx-rtmp/nginx.conf: file does not exist`

After that you receive the message that the build has failed.

**Comment by ngrie** [comment]
The root `docker-compose.yaml` ist intended for development only. Please read https://github.com/ngrie/rtmpie/issues/5#issuecomment-700857147 for further instructions.
