### ISSUE TITLE
Database Access not working

### ISSUE THREAD

**Issue by TacticalNoobs** [ngrie/rtmpie#20]
Hello,

It looks like it trys to access an database that is not on my Server (different IP Address).

![image](https://user-images.githubusercontent.com/95185968/143781463-e266ed12-af24-4353-a64c-4dc32aa058dc.png)

**Comment by ngrie** [comment]
Please follow the [installation instructions](https://github.com/ngrie/rtmpie#installation) to set up your installation. This should configure everything correctly.

**Comment by TacticalNoobs** [comment]
I had to reinstall the complete server. The problem was i have changed the Admin password. And as it seems this has lead to the error. Now everything is running. But would it be possible to define in the setup.sh already an own Admin password?

**Comment by ngrie** [comment]
The admin password is always "admin" by default, but can be changed using the web interface.
