### ISSUE TITLE
Any way to restore forgotten password or recover user.

### ISSUE THREAD

**Issue by karma-rohit** [ngrie/rtmpie#21]
I change the default password of the Admin from the profile settings, but saved the wrong password (any character missing). And now I don’t get access to the Dashboard. 

Is there any way to change password, like forgot password feature. Or change from the file where the password got saved. 

Thanks

**Comment by ngrie** [comment]
You can delete all users, then on the next start, a new admin user with the default password will be created.
It should work by running these commands (assuming you installed RTMPie the way it is described [in the readme](https://github.com/ngrie/rtmpie#installation)):
```
cd /opt/rtmpie # or whatever your installation folder is
source <(grep RTMPIE_DATABASE_PASSWORD rtmpie.conf)
# WARNING: This will delete all users in your RTMPie installation
docker-compose exec database mysql -uroot -p$RTMPIE_DATABASE_PASSWORD -e "USE rtmpie; DELETE FROM user;"
docker-compose restart php
```
