### ISSUE TITLE
A way to just run rtmpie without Caddy?

### ISSUE THREAD

**Issue by dillfrescott** [ngrie/rtmpie#22]
On my server I already have Caddy running for other services, and with two Caddy's going it kind of freaks out about redirecting the page improperly and what not.

Is there a way to run rtmpie without the Caddy?

**Comment by ngrie** [comment]
RTMPie cannot work properly without its own Caddy server. However it should be possible to use your own Caddy (or any other webserver like NGINX or Apache) as a reverse proxy.

**Comment by dillfrescott** [comment]
Got it! Thank you for the info!
