### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by DJKenzoDE** [ngrie/rtmpie#23]
the webinterface say on the stream page connection lost

Screenshot
https://prnt.sc/24t0dpj

how to fix that?
i have installed with your tutorial on ubuntu 20.04

**Comment by ngrie** [comment]
Is that message always there or does it appear after a few minutes?

**Comment by DJKenzoDE** [comment]
always

**Comment by ngrie** [comment]
Closed due to inactivity
