### ISSUE TITLE
Where do find files ?

### ISSUE THREAD

**Issue by trapzed** [ngrie/rtmpie#24]
Hey,

I used the installer in the read.me and i get this folder but where are the web files ? 
To edit and create routes etc
![Screenshot](https://user-images.githubusercontent.com/97110485/167210430-cade1339-4b63-457d-aae3-db058d924f00.png)

**Comment by ngrie** [comment]
Hi,

the readme describes the production setup where all the source code comes with the docker image you download using `docker-compose pull`. You cannot make any modifications.

If you like to start developing on RTMPie, you instead need to clone the repository and create a local development setup yourself, e.g. using the [Symfony CLI](https://symfony.com/download).

**Comment by trapzed** [comment]
So you need to install rtmp server and to configure route etc ?

**Comment by trapzed** [comment]
Can you provide a tutorial to install it pls ?

**Comment by ngrie** [comment]
If I recall correctly, and assuming you have the Symfony CLI installed, setup should be:
```
symfony server:start -d
docker-compose up -d
```
This runs the PHP process using the CLI and database & RTMP server is running in docker.

**Comment by trapzed** [comment]
![Screenshot_125](https://user-images.githubusercontent.com/97110485/167491307-8558ca72-9e90-4676-88e5-dbc8f7b06654.png)

**Comment by ngrie** [comment]
Closed due to inactivity
