### ISSUE TITLE
Broken execution

### ISSUE THREAD

**Issue by mteichtahl** [ngrie/rtmpie#25]
It seems something has broken recently

tmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
php_1       | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
caddy_1     | standard_init_linux.go:207: exec user process caused "exec format error"
rtmpie_rtmp_1 exited with code 1
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
rtmp_1      | standard_init_linux.go:207: exec user process caused "exec format error"
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by ngrie** [comment]
Closed due to inactivity
