### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by TheSkream** [ngrie/rtmpie#5]
Hello,

I have this error when i execute this :

```
root@rtmp-srv:~/rtmpie# docker-compose up -d
Building rtmp
Step 1/6 : FROM ngrie/nginx-rtmp:latest
 ---> 70a28dc6bf61
Step 2/6 : RUN apk --no-cache add ffmpeg
 ---> Using cache
 ---> 106c0ad6f607
Step 3/6 : RUN mkdir -p /var/thumbnails /tmp/thumbnail_recordings &&     chown -R nginx:nginx /var/thumbnails &&     chmod -R 770 /var/thumbnails &&   
  chown -R nginx:nginx /tmp/thumbnail_recordings &&     chmod -R 770 /tmp/thumbnail_recordings
 ---> Using cache
 ---> ce37b47ba986
Step 4/6 : COPY docker/nginx-rtmp/nginx.conf /etc/nginx/nginx.conf
ERROR: Service 'rtmp' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder359824000/docker/nginx-rtmp/nginx.conf: no such file or directory
root@rtmp-srv:~/rtmpie# 
```

Can you help me ?

Thx.

**Comment by ngrie** [comment]
Hi,

the docker compose setup in the root directory is meant for development purposes. If your intention is to simply run the software, try:

```
docker-compose -f ./docker/docker-compose.prod.yaml build
docker-compose -f ./docker/docker-compose.prod.yaml up -d
```

Normally you would not even have to checkout the git repository to use RTMPie, but documenting the installation process is still on my todo list ... so feel free to ask here if you are getting stuck again during the setup process.

**Comment by TheSkream** [comment]
Oh thx it's good.

I see that we cannot make a redirect on another platform. Whereas nginx normally allows it.
Is it complicated to set this up via the interface ?

Thanks.

**Comment by ngrie** [comment]
True, this is currently not possible to set up using RTMPie.

The primary goal of RTMPie is not to make every feature of the NGINX RTMP module configurable using the webinterface, but to offer additional functionality such as a comfortable stream management including authentication (stream keys), thumbnails, live statistics and more. Implementing a stream redirection feature would be a nice addition and is planned but I cannot tell when this will be available.

**Comment by TheSkream** [comment]
Okay no worries, it was just a simple question.
Thanks for taking time to respond to me.
In any case, good work.
