### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by slimako** [ngrie/rtmpie#9]
Hi, 
I have a problem with this project. 

Connection lost
This page may display outdated information due to connection issues.

![image](https://user-images.githubusercontent.com/28524855/106034502-48c26f00-60d3-11eb-826b-d717d3c66c3c.png)
`nginx_1     | 2021/01/27 18:08:26 [error] 28#28: *15 connect() failed (113: Host is unreachable) while connecting to upstream, client: ip, server: , request: "GET /.well-known/mercure?topic=%2Fapi%2Fstreams%2F%7Bid%7D&topic=http%3A%2F%2Fip%3A8080%2Fapi%2Fstreams%2F%7Bid%7D HTTP/1.1", upstream: "http://172.18.0.6:80/.well-known/mercure?topic=%2Fapi%2Fstreams%2F%7Bid%7D&topic=http%3A%2F%2Fip%3A8080%2Fapi%2Fstreams%2F%7Bid%7D", host: "ip:8080", referrer: "http://ip:8080/admin/streams"`

os: debian 9 and 10 on ubuntu does not start
Docker version 19.03.14, build 5eb3275d40
docker-compose version 1.28.2, build 67630359

How to fix it?

**Comment by ngrie** [comment]
Hi, ist the `mercure` container running? How did you install/start RTMPie?

**Comment by slimako** [comment]
I used these commands for installation
`docker-compose -f ./docker/docker-compose.prod.yaml build
docker-compose -f ./docker/docker-compose.prod.yaml up -d
`

![image](https://user-images.githubusercontent.com/28524855/106119824-e9597300-6155-11eb-8fe2-6ab29e77e0a7.png)

**Comment by ngrie** [comment]
Looks like mercure pushed an update which needs some changes on my end. For now, please try appending [this line in docker-compose.prod.yaml](https://github.com/ngrie/rtmpie/blob/master/docker/docker-compose.prod.yaml#L38) and adding `:v0.9`:

```yaml
image: dunglas/mercure:v0.9
```

I will look into this later.

**Comment by modm12** [comment]
Hi @ngrie  
I have problems with the installation of the rtmp service, can not find the file, can I skip the step and where do I have to save the file? 
![imagen](https://user-images.githubusercontent.com/6964271/114963955-0c2d2680-9e2b-11eb-9a05-b18e762f3a13.png)
